name: Java CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Add required environment
        run: echo ${{ secrets.TEST_BOT_TOKEN }} >> demo-application/src/main/resources/application.properties
      - name: Build with Maven
        run: mvn clean test package
